const DB=JSON.parse(localStorage.bpx5||'{"budget":3000000,"cats":["ที่ดิน","ถมที่","เคลียริ่ง","โครงสร้าง","เขื่อน","ถนน","ไฟฟ้า","เครื่องใช้ไฟฟ้า","อุปกรณ์ตกแต่ง","รั้วบ้าน","จัดสวน"],"items":[],"con":[],"due":[]}');
const $=id=>document.getElementById(id);let edit=-1,chart;
const els={open:$("open"),close:$("close"),modal:$("modal"),name:$("name"),amt:$("amt"),cat:$("cat"),addCat:$("addCat"),newCat:$("newCat"),saveExpense:$("saveExpense"),saveCon:$("saveCon"),cn:$("cn"),cp:$("cp"),saveDue:$("saveDue"),due:$("due"),saveBudget:$("saveBudget"),budgetInput:$("budgetInput"),backup:$("backup"),restoreFile:$("restoreFile"),search:$("search"),budgetList:$("budgetList"),list:$("list"),cons:$("cons"),dues:$("dues"),pie:$("pie"),total:$("total"),spent:$("spent"),remain:$("remain"),pct:$("pct")};
document.querySelectorAll('#nav button').forEach((b,i)=>{if(i===0)b.classList.add('active');b.addEventListener('click',()=>{document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));$(b.dataset.page).classList.add('active');document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');});});
function persist(){localStorage.bpx5=JSON.stringify(DB);render();}
els.open.addEventListener('click',()=>{edit=-1;els.name.value='';els.amt.value='';els.modal.classList.remove('hide');});
els.close.addEventListener('click',()=>els.modal.classList.add('hide'));
els.addCat.addEventListener('click',()=>{const c=els.newCat.value.trim();if(c&&!DB.cats.includes(c)){DB.cats.push(c);els.newCat.value='';persist();}});
els.saveExpense.addEventListener('click',()=>{if(!els.name.value||!els.amt.value)return alert('กรอกข้อมูล');const obj={n:els.name.value,c:els.cat.value,a:+els.amt.value};if(edit>=0)DB.items[edit]=obj;else DB.items.push(obj);els.modal.classList.add('hide');persist();});
window.editItem=i=>{edit=i;const x=DB.items[i];els.name.value=x.n;els.cat.value=x.c;els.amt.value=x.a;els.modal.classList.remove('hide');};
window.delItem=i=>{if(confirm('ลบรายการนี้?')){DB.items.splice(i,1);persist();}};
els.saveCon.addEventListener('click',()=>{if(els.cn.value){DB.con.push({n:els.cn.value,p:els.cp.value});els.cn.value='';els.cp.value='';persist();}});
els.saveDue.addEventListener('click',()=>{if(els.due.value){DB.due.push(els.due.value);els.due.value='';persist();}});
els.saveBudget.addEventListener('click',()=>{DB.budget=+els.budgetInput.value||DB.budget;persist();});
els.backup.addEventListener('click',()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(DB)],{type:'application/json'}));a.download='BudgetProX-Backup.json';a.click();});
els.restoreFile.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{Object.assign(DB,JSON.parse(r.result));persist();};r.readAsText(f);});
els.search.addEventListener('input',render);
function render(){els.budgetInput.value=DB.budget;els.cat.innerHTML=DB.cats.map(c=>`<option>${c}</option>`).join('');const sums={};DB.cats.forEach(c=>sums[c]=0);DB.items.forEach(i=>sums[i.c]=(sums[i.c]||0)+i.a);const spentVal=DB.items.reduce((a,b)=>a+b.a,0);els.total.textContent=DB.budget.toLocaleString();els.spent.textContent=spentVal.toLocaleString();els.remain.textContent=(DB.budget-spentVal).toLocaleString();els.pct.textContent=Math.round(spentVal/DB.budget*100)+'%';els.budgetList.innerHTML=DB.cats.map(c=>`<div class=row><span>${c}</span><b>${(sums[c]||0).toLocaleString()}</b></div>`).join('');const q=(els.search.value||'').toLowerCase();els.list.innerHTML=DB.items.map((e,i)=>({e,i})).filter(o=>o.e.n.toLowerCase().includes(q)||o.e.c.toLowerCase().includes(q)).map(o=>`<div class=row><div><b>${o.e.n}</b><br>${o.e.c}</div><div><div>${o.e.a.toLocaleString()}</div><button class=small onclick='editItem(${o.i})'>✏️</button><button class=small onclick='delItem(${o.i})'>🗑️</button></div></div>`).join('')||'ยังไม่มีรายการ';els.cons.innerHTML=DB.con.map(c=>`<div class=row><span>${c.n}</span><span>${c.p}</span></div>`).join('')||'ยังไม่มีผู้รับเหมา';els.dues.innerHTML=DB.due.map(d=>`<div class=row><span>ครบกำหนด</span><span>${d}</span></div>`).join('')||'ยังไม่มีงวด';if(window.Chart){if(chart)chart.destroy();chart=new Chart(els.pie,{type:'pie',data:{labels:DB.cats,datasets:[{data:DB.cats.map(c=>sums[c])}]},options:{plugins:{legend:{position:'bottom'}}}});} }
render();